package:
  name: arrowmanager
  version: 0.1

source:
  path: ..

requirements:
  build:
    - python >=3
    - setuptools
    - sqlalchemy
    - flask
    - flask-restful # conda-forge
    - flask-script # conda-forge
    - flask-assets # conda-forge
    - flask-cors # conda-forge
    - passlib
#    - pip install flask-jwt-extended
#    - pip install flask-sqlalchemy
#    - pip install flask-migrate # conda-forge version is out of date
#    - pip install flask-caching
#    - pip install Flask-Stormpath
#    - pip install git+https://github.com/kubernetes-incubator/client-python.git

  run:
    - python
    - click

  test:
    - pytest
    - factory_boy # conda-forge
    - webtest