"""empty message

Revision ID: 32da94708f0d
Revises: 
Create Date: 2016-12-08 21:05:25.706212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32da94708f0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(), nullable=False),
    sa.Column('git_rev', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('buildtime', sa.DateTime(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build')
    op.drop_table('application')
    ### end Alembic commands ###
